config/routes.rb
Rails.application.routes.draw do

  devise_for :users
	resources :posts do
		member do
			get "like", to: "posts#upvote"
			get "dislike", to: "posts#downvote"
		end
		resources :comments
	end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
	
	acts_as_votable
	belongs_to :user
	has_attached_file :image, styles: { medium: "1000x800#", small: "110x70#" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected 

  def configure_permitted_parameters
  	devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  	devise_parameter_sanitizer.permit(:account_update, keys: [:name])  	
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	before_action :authenticate_user!

	def create
		@post = Post.find(params[:post_id])
		@comment = Comment.create(params[:comment].permit(:content))
		@comment.user_id = current_user.id
		@comment.post_id = @post.id

		if @comment.save
			redirect_to post_path(@post)
		else
			render 'new'
		end
	end
	def destroy
		
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  before_action :find_post, only: [:show, :edit, :update,:destroy, :upvote, :downvote]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @posts = Post.all.order("created_at DESC")
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end
  def edit
  end
  def update
    if @post.update(post_params)
      redirect_to @post
    else 
      render 'edit'
    end
  end
  def destroy
    @post.destroy
    redirect_to root_path
  end

  def show
    @comments = Comment.where(post_id: @post)
  end
  def upvote
    @post.upvote_by current_user
    redirect_to root_path
  end
  def downvote
    @post.downvote_by current_user
    redirect_to root_path 
  end

  private

  def find_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :link, :description, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_form.html.erb
<%= simple_form_for([@post, @post.comments.build]) do |f| %>
	<%= f.input :content, label: "Reply to Thread" %>
	<%= f.button :submit, class: "btn btn-primary"%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Art</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Indie+Flower" rel="stylesheet">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="header">
      <div class="wrapper clearfix">
        <div id="logo">
          <%= link_to "Art", root_path %>
        </div>           
        <ul class="nav pull-right">
          <% if user_signed_in? %>
          <%= link_to current_user.name , edit_user_registration_path %>
            <%= link_to "New Post", new_post_path %>             
          <%= link_to "Sign out", destroy_user_session_path, method: :delete%>
          <% else %>  
          <%= link_to "Sign In", new_user_session_path %>
          <%= link_to "Sign Up", new_user_registration_path %>
          <% end %>
        </ul>            
      </div>
    </div>
  	<p class="notice alert"><%= notice %></p>
    <p class="alert"><%= alert %></p>  
    <div class="wrapper">
      <%= yield %>
    </div>
    
  </body>
</html>

app/views/posts/_form.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6">
			<%= simple_form_for @post do |f| %>
				<%= f.input :image %>
				<%= f.input :title %>
				<%= f.input :link %>
				<%= f.input :description %>
				<%= f.button :submit ,class: "btn btn-primary" %>
			<% end %>
		</div>
	</div>
</div>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6">
			<h1>Edit Inspiration</h1>
			<%= render 'form' %>
			<%= link_to "Back", root_path %>
		</div>
	</div>
</div>

app/views/posts/index.html.erb
<div class="container">
		<% if user_signed_in? %>
			<p id="intro">Hello <%= current_user.name %><br>
				<span>Share your Inspiraation and see what's inspiring others.</span>
			</p>
			<% else %>
				<p id="intro">What is your insp?<br>
					<span>Share your Inspiraation and see what's inspiring others.</span>
				</p>
		<% end %>
	<div id="posts">
		<% @posts.each do |post| %>
		<div class="post">
			<div class="post_image">
				<%= link_to (image_tag post.image.url(:small)), post %>
			</div>
			<div class="post_content">
				<div class="title">
					<h2><%= link_to post.title, post %></h2>
				</div>
				<div class="data clearfix">
					<p class="username">
						Shared by <%= post.user.name%>
					</p>
					<p class="buttons">
						<span><i class="fa fa-comments-o"><%= post.comments.count %></i></span> | 
						<span><i class="fa fa-thumbs-o-up"><%= post.get_likes.size %></i></span>
					</p>
				</div>
			</div>
		</div>
		<% end %>	
	</div>		
</div>

app/views/posts/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6">
			<h1>Add New Inspiration</h1>
			<%= render 'form' %>
			<%= link_to "Back", root_path %>
		</div>
	</div>
</div>

app/views/posts/show.html.erb
<div class="container">
	<div class="row">		
		<h1><%= @post.title %></h1>
		<p class="username">Shared by <%= @post.user.name %> about <%= time_ago_in_words(@post.created_at)%></p>
		<div class="post_image_description"><%= image_tag @post.image.url(:medium) %>
			<div class="description"><%= simple_format(@post.description) %></div>
		</div>
		<div class="post_data">
			<%= link_to "Visit Link", @post.link, class: "button" %>
			<%= link_to like_post_path(@post), method: :get, class: "data" do %>
			<i class="fa fa-thumbs-o-up"><%= pluralize(@post.get_upvotes.size, "Like" ) %></i>
			<% end %>
			<%= link_to dislike_post_path(@post), method: :get, class: "data" do %>
			<i class="fa fa-thumbs-o-down"><%= pluralize(@post.get_downvotes.size, "Dislike" ) %></i>
			<% end %><br><br>
			<p class="data"><i class="fa fa-comments-o"><%= pluralize(@post.comments.count, "Comment")  %></i></p>
			<% if @post.user = current_user %>
				<div class="btn-group">
				<%= link_to "Edit", edit_post_path(@post) , class: "btn btn-default" %>
				<%= link_to "Back", root_path , class: "btn btn-default" %>
				<%= link_to "Delete", post_path(@post), method: :delete, data: {confirm: "Are you sure?" } , class: "btn btn-danger" %>
			<% end %>
	</div>
		</div>
		<small><%= @post.link %></small>
	</div>
	<div id="comment">
		<h2 class="comment_count"><%= pluralize(@post.comments.count, "Comment") %></h2>
		<% @comments.each do |comment| %>
			<div class="comment">
				<p class="content"><%= comment.content %></p>
				<span class="username" id="username"><small><%= comment.user.name %></small></span>				
			</div>
		<% end %>
		<%= render 'comments/form' %>
	</div>
</div>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>